### PR TITLE
Feature/paging rebased

### PR DESCRIPTION
**Pull request by aspasia**
- This adds pagination to list-transactions with some defaults in order to not blow up the JVM. 
- Currency was added as a  query criteria
- Tests written to support all of the above.

@jaromil can you please have a look?

### CODE REVIEW

**Comment by aspasia** [comment]
@jaromil hm that's a very good point actually. What is now returned is the 10 first entries unless the paging is otherwise specified (max 100 pp). This is documented on swagger. However there is no way currenctly for a SWAPI user to find out how many transactions/or pages are left. One can increase keep increasing the page number and at some point the next page will be empty or with less entries than the ones asked. But you are right, would be useful to have some indication on how many to expect, how do you imagine this with respect to the response? I am looking a bit around on REST API principles, how it is usually implemented. From the top of my head I don't remember APIs returning such info, usually with paging there is something like previous/next and maybe last. I will look a bit around, maybe something like `page 2/20` would be nice on top of every response?

**Comment by jaromil** [comment]
ack. From a caller POV I imagine would be enough to receive the current page and the total records, then one can calculate anything else. Receiving the pages left is sort of redundant. Receiving the index (absolute position of first item listed in current page) may be handy. I imagine callers will first and foremost be able to create a footer with current pages, pages left, total hits (a'la search engines).

**Comment by aspasia** [comment]
yep another confirmation it is the way to go https://stackoverflow.com/questions/3715981/what-s-the-best-restful-method-to-return-total-number-of-items-in-an-object/3716040#3716040, I am on it :)

**Comment by aspasia** [comment]
@jaromil I fixed the issue you mentioned, now there is a function `count-transactions`

**Pull request merged**
